In [1]:
import pandas as pd

# 创建方式 1
df1 = pd.DataFrame({'id':[101,102,103],
              'name':["tom","alex","alen"],
              'age':[7,8,9]})
df1

    id  name  age
0  101   tom    7
1  102  alex    8
2  103  alen    9

In [2]:
# 创建方式 2
df2 = pd.DataFrame(data= {'id':[101,102,103],"name":["tom","alex","alen"]},columns=['id','name'], index =[101,102,103])
df2

      id  name
101  101   tom
102  102  alex
103  103  alen

In [7]:
print(df2.index) #获取索引
print(df2.columns)
print(df2.values)
print(df2.shape)
print(df2.dtypes)

Index([101, 102, 103], dtype='int64')
Index(['id', 'name'], dtype='str')
[[101 'tom']
 [102 'alex']
 [103 'alen']]
(3, 2)
id      int64
name      str
dtype: object

In [8]:
print(df1.T)

        0     1     2
id    101   102   103
name  tom  alex  alen
age     7     8     9

In [11]:
df1.iloc[0:3,2]

0    7
1    8
2    9
Name: age, dtype: int64

In [22]:
df2.at[101,"name"]

'tom'

In [23]:
print(df1.isna())

      id   name    age
0  False  False  False
1  False  False  False
2  False  False  False

In [25]:
df1["age"].min()

np.int64(7)

In [26]:
df1["age"].max()

np.int64(9)

In [27]:
df1["age"].var()

np.float64(1.0)

In [28]:
df1.info()

<class 'pandas.DataFrame'>
RangeIndex: 3 entries, 0 to 2
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   id      3 non-null      int64
 1   name    3 non-null      str
 2   age     3 non-null      int64
dtypes: int64(2), str(1)
memory usage: 204.0 bytes