In [1]:
import pandas as pd
df = pd.DataFrame({"gmv":[100,200,300,400],"trade_date":["2024-01-06","2026-06-08","2025-11-23","2026-04-23"]})

# 新增一列dataframe，转化为日期类型
df["ymd"]=pd.to_datetime(df["trade_date"])
df

   gmv  trade_date        ymd
0  100  2024-01-06 2024-01-06
1  200  2026-06-08 2026-06-08
2  300  2025-11-23 2025-11-23
3  400  2026-04-23 2026-04-23

In [2]:
df["yy"],df["mm"],df["dd"]= df["ymd"].dt.year,df["ymd"].dt.month,df["ymd"].dt.day
df

   gmv  trade_date        ymd    yy  mm  dd
0  100  2024-01-06 2024-01-06  2024   1   6
1  200  2026-06-08 2026-06-08  2026   6   8
2  300  2025-11-23 2025-11-23  2025  11  23
3  400  2026-04-23 2026-04-23  2026   4  23

In [3]:
df["week"]=df["ymd"].dt.day_name()
df

   gmv  trade_date        ymd    yy  mm  dd      week
0  100  2024-01-06 2024-01-06  2024   1   6  Saturday
1  200  2026-06-08 2026-06-08  2026   6   8    Monday
2  300  2025-11-23 2025-11-23  2025  11  23    Sunday
3  400  2026-04-23 2026-04-23  2026   4  23  Thursday