In [2]:
import pandas as pd

s1=pd.Series(["A","B"],index=[1,2])
s2=pd.Series(["C","D"],index=[3,4])
s3=pd.Series(["E","F"],index=[5,6])

#默认按行拼接（竖着列下去）
pd.concat([s1,s2,s3])

1    A
2    B
3    C
4    D
5    E
6    F
dtype: str

In [3]:
#按照索引对齐（没有索引的nan）
pd.concat([s1,s2,s3],axis=1)

     0    1    2
1    A  NaN  NaN
2    B  NaN  NaN
3  NaN    C  NaN
4  NaN    D  NaN
5  NaN  NaN    E
6  NaN  NaN    F

In [4]:
df1=pd.DataFrame(data={"a":[1,2],"b":[3,4]},index=[1,2])

s1=pd.Series(data=[7,10],index=[1,2],name="a")
pd.concat([df1,s1])

    a    b
1   1  3.0
2   2  4.0
1   7  NaN
2  10  NaN

In [5]:
pd.concat([df1,s1],axis=1)

   a  b   a
1  1  3   7
2  2  4  10

In [11]:
df1=pd.DataFrame(data={"a":[1,2],"b":[3,4]},index=[1,2])
df2=pd.DataFrame(data={"a":[7,8],"b":[9,10]},index=[1,2])
pd.concat([df1,df2],ignore_index=True)

     a  b     c
0  1.0  3   NaN
1  2.0  4   NaN
2  NaN  7   9.0
3  NaN  8  10.0

In [12]:
df1=pd.DataFrame(data={"a":[1,2],"b":[3,4]},index=[1,2])
df2=pd.DataFrame(data={"b":[7,8],"c":[9,10]},index=[2,3])
# join=outer 并集，保留所有行、列，没有的用nan填充

pd.concat([df1,df2])

     a  b     c
1  1.0  3   NaN
2  2.0  4   NaN
2  NaN  7   9.0
3  NaN  8  10.0

In [13]:
pd.concat([df1,df2],join="inner")

   b
1  3
2  4
2  7
3  8