In [17]:
import pandas as pd

df1 = pd.DataFrame({"employee": ["Bob", "Jake", "Lisa", "Sue"],"group": ["Accounting", "Engineering", "Engineering", "HR"]})
df2 = pd.DataFrame({"name": ["Lisa","Bob","Jake","Sue"],"hire_date":[2004,2008,2012,2014]})

In [18]:
pd.merge(df1, df2, left_on="employee", right_on="name")

  employee        group  name  hire_date
0      Bob   Accounting   Bob       2008
1     Jake  Engineering  Jake       2012
2     Lisa  Engineering  Lisa       2004
3      Sue           HR   Sue       2014

In [19]:
df2 = pd.DataFrame({
    "group":["Accounting","Accounting", "Engineering", "Engineering", "HR", "HR"],
    "skills":["math","spreadsheets","coding","linux","spreadsheets","organization"],
})
df2

         group        skills
0   Accounting          math
1   Accounting  spreadsheets
2  Engineering        coding
3  Engineering         linux
4           HR  spreadsheets
5           HR  organization

In [20]:
pd.merge(df1, df2)

  employee        group        skills
0      Bob   Accounting          math
1      Bob   Accounting  spreadsheets
2     Jake  Engineering        coding
3     Jake  Engineering         linux
4     Lisa  Engineering        coding
5     Lisa  Engineering         linux
6      Sue           HR  spreadsheets
7      Sue           HR  organization

In [21]:
df1 = pd.DataFrame({"employee": ["Bob", "Jake", "Lisa", "Sue"],"group": ["Accounting", "Engineering", "Engineering", "HR"]})
df2 = pd.DataFrame({"employee": ["Lisa","Bob","Jake","Sue"],"hire_date":[2004,2008,2012,2014]})

df1.set_index("employee", inplace=True)
df2.set_index("employee", inplace=True)

pd.merge(df1, df2,left_index=True, right_index=True)

                group  hire_date
employee
Bob        Accounting       2008
Jake      Engineering       2012
Lisa      Engineering       2004
Sue                HR       2014

In [ ]:
# join()默认按照索引合并——同名列必须加lsuffix=‘_left', rsuffix='_right'